# Generated by Django 5.1.1 on 2026-06-20 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_user_and_commission_rate'),
        ('commissions', '0001_initial'),
        ('orders', '0001_initial'),
        ('sellers', '0004_make_user_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('link_created', 'Link Created'), ('link_opened', 'Link Opened'), ('checkout_started', 'Checkout Started'), ('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed'), ('payment_expired', 'Payment Expired'), ('payment_refunded', 'Payment Refunded'), ('payment_chargeback', 'Payment Chargeback'), ('seller_credentials', 'Seller Credentials'), ('commission_paid', 'Commission Paid')], max_length=50)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('internal', 'Internal Notification')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(help_text='Supports Django template variables: {{vendedor}}, {{usuario}}, {{senha}}, {{periodo}}, {{valor}}, {{cliente}}, {{link}}')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'event_type'], name='notificatio_tenant__c00ef8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('link_created', 'Link Created'), ('link_opened', 'Link Opened'), ('checkout_started', 'Checkout Started'), ('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed'), ('payment_expired', 'Payment Expired'), ('payment_refunded', 'Payment Refunded'), ('payment_chargeback', 'Payment Chargeback'), ('seller_credentials', 'Seller Credentials'), ('commission_paid', 'Commission Paid')], default='link_created', max_length=50)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('internal', 'Internal Notification')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='commissions.commissionperiod')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sellers.seller')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'event_type', 'status'], name='notificatio_tenant__38c245_idx'), models.Index(fields=['order', 'status'], name='notificatio_order_i_e450b9_idx')],
            },
        ),
    ]
