# Generated by Django 5.1.1 on 2026-06-25 02:31

import app.apps.accounts.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresetrequest',
            name='notificatio_pin_a5773f_idx',
        ),
        migrations.RemoveField(
            model_name='passwordresetrequest',
            name='pin',
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='pin_hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_body',
            field=app.apps.accounts.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=app.apps.accounts.fields.EncryptedCharField(max_length=600),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_ea4bd9_idx'),
        ),
    ]
