# Generated by Django 5.1.1 on 2026-06-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_link_canceled_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='event_type',
            field=models.CharField(choices=[('link_created', 'Link Created'), ('link_canceled', 'Link Canceled'), ('link_opened', 'Link Opened'), ('checkout_started', 'Checkout Started'), ('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed'), ('payment_expired', 'Payment Expired'), ('payment_refunded', 'Payment Refunded'), ('payment_chargeback', 'Payment Chargeback'), ('seller_credentials', 'Seller Credentials'), ('commission_paid', 'Commission Paid'), ('commission_adjusted', 'Commission Adjusted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('link_created', 'Link Created'), ('link_canceled', 'Link Canceled'), ('link_opened', 'Link Opened'), ('checkout_started', 'Checkout Started'), ('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed'), ('payment_expired', 'Payment Expired'), ('payment_refunded', 'Payment Refunded'), ('payment_chargeback', 'Payment Chargeback'), ('seller_credentials', 'Seller Credentials'), ('commission_paid', 'Commission Paid'), ('commission_adjusted', 'Commission Adjusted')], default='link_created', max_length=50),
        ),
    ]
