# Generated by Django 5.1.1 on 2026-07-04 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_ranking_visible_default_false'),
        ('notifications', '0004_alter_messagetemplate_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='event_type',
            field=models.CharField(choices=[('link_created', 'Link Created'), ('link_canceled', 'Link Canceled'), ('link_opened', 'Link Opened'), ('checkout_started', 'Checkout Started'), ('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed'), ('payment_expired', 'Payment Expired'), ('payment_refunded', 'Payment Refunded'), ('payment_chargeback', 'Payment Chargeback'), ('seller_credentials', 'Seller Credentials'), ('commission_paid', 'Commission Paid'), ('commission_adjusted', 'Commission Adjusted'), ('daily_reminder', 'Daily Reminder')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('link_created', 'Link Created'), ('link_canceled', 'Link Canceled'), ('link_opened', 'Link Opened'), ('checkout_started', 'Checkout Started'), ('payment_paid', 'Payment Paid'), ('payment_failed', 'Payment Failed'), ('payment_expired', 'Payment Expired'), ('payment_refunded', 'Payment Refunded'), ('payment_chargeback', 'Payment Chargeback'), ('seller_credentials', 'Seller Credentials'), ('commission_paid', 'Commission Paid'), ('commission_adjusted', 'Commission Adjusted'), ('daily_reminder', 'Daily Reminder')], default='link_created', max_length=50),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='accounts.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'endpoint'), name='unique_user_endpoint')],
            },
        ),
    ]
