# Generated by Django 5.1.1 on 2026-07-04 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_onboarding_progress'),
        ('notifications', '0005_push_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_emails', to='accounts.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'trigger'), name='unique_tenant_trigger')],
            },
        ),
    ]
