# Generated by Django 5.1.1 on 2026-07-08 02:45

import app.apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_lifecycle_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='secondary_body',
            field=app.apps.accounts.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
