# Generated by Django 5.1.1 on 2026-06-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_encrypted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('ESSENCIAL', 'Essencial (ate 5 vendedores)'), ('PROFISSIONAL', 'Profissional (ate 15 vendedores)'), ('PLUS', 'Plus (ate 30 vendedores)'), ('ENTERPRISE', 'Enterprise (ilimitado)')], default='ESSENCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
