# Generated by Django 5.1.1 on 2026-06-25 02:31

import app.apps.accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_user_user_tenant_role_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cnpj_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='cnpj',
            field=app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600, null=True),
        ),
    ]
