# Generated by Django 5.1.1 on 2026-06-26 19:19

import app.apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenant_cnpj_hash_alter_tenant_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='pagarme_api_key',
            field=app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='whatsapp_token',
            field=app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600, null=True),
        ),
    ]
