# Generated by Django 5.1.1 on 2026-06-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_tenant_pagarme_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='link_expires_in',
            field=models.PositiveIntegerField(
                default=1200,
                help_text='Tempo de expiracao do link de pagamento em minutos (padrao 1200 = 20h)',
            ),
        ),
    ]
