# Generated by Django 5.1.1 on 2026-07-01 17:50

import app.apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_tenant_pix_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pagarme_webhook_password',
            field=app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pagarme_webhook_username',
            field=app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600, null=True),
        ),
    ]
