# Generated by Django 5.1.1 on 2026-07-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_webhook_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='daily_reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='daily_reminder_time',
            field=models.TimeField(default='20:00'),
        ),
    ]
