# Generated by Django 5.1.1 on 2026-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_tenant_daily_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ranking_visible_to_sellers',
            field=models.BooleanField(default=True, help_text='Vendedor ve ranking completo com nomes dos colegas'),
        ),
    ]
