# Generated by Django 5.1.1 on 2026-07-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_tenant_ranking_visible_to_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
