# Generated by Django 5.1.1 on 2026-07-04 02:52

from django.db import migrations, models


def migrate_enterprise_to_business(apps, schema_editor):
    Tenant = apps.get_model('accounts', 'Tenant')
    Tenant.objects.filter(plan='ENTERPRISE').update(plan='BUSINESS')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_ranking_visible_default_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20),
        ),
        migrations.RunPython(migrate_enterprise_to_business, reverse_code=noop),
    ]
