# Generated by Django 5.1.1 on 2026-07-04 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_enterprise_to_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_whatsapp', models.BooleanField(default=False)),
                ('step_sellers', models.BooleanField(default=False)),
                ('step_commission_rate', models.BooleanField(default=False)),
                ('step_first_invite', models.BooleanField(default=False)),
                ('step_first_sale', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='accounts.tenant')),
            ],
        ),
    ]
