# Generated by Django 5.1.1 on 2026-07-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_onboarding_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accountant_auto_send',
            field=models.BooleanField(default=False, help_text='Enviar automaticamente o pacote contabil quando todas as comissoes da competencia forem pagas'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='accountant_email',
            field=models.EmailField(blank=True, help_text='E-mail da contabilidade para envio automatico do fechamento mensal', max_length=254, null=True),
        ),
    ]
