# Generated by Django 5.1.1 on 2026-07-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_correios_cws_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='skip_national_holidays',
            field=models.BooleanField(default=True, help_text='Nao cobrar lancamentos em feriados nacionais'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='working_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Dias de funcionamento (0=seg ... 6=dom). Vazio = seg a sab.'),
        ),
    ]
