# Generated by Django 5.1.1 on 2026-07-10 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_tenant_skip_national_holidays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='period_start_day',
            field=models.PositiveSmallIntegerField(default=21, help_text='Dia de inicio do ciclo de comissao (ex.: 21 sugere periodos de 21 a 20).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
