# Generated by Django 5.1.1 on 2026-07-10 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_tenant_skip_national_holidays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='period_start_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Dia de inicio do periodo de comissao (1 = mes-calendario).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
