# Generated by Django 5.1.1 on 2026-06-25 02:31

import app.apps.accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=app.apps.accounts.fields.EncryptedCharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600, null=True),
        ),
    ]
