# Generated by Django 5.1.1 on 2026-07-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_customer_name_alter_order_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='gateway_link_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
