# Generated by Django 5.1.1 on 2026-06-24 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenant_slug'),
        ('sellers', '0005_normalize_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seller',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='unique_tenant_phone'),
        ),
    ]
