# Generated by Django 5.1.1 on 2026-06-25 02:31

import app.apps.accounts.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenant_cnpj_hash_alter_tenant_cnpj'),
        ('sellers', '0006_unique_tenant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seller',
            name='unique_tenant_phone',
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=app.apps.accounts.fields.EncryptedCharField(max_length=600),
        ),
        migrations.AddConstraint(
            model_name='seller',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone_hash'), name='unique_tenant_phone'),
        ),
    ]
