# Generated by Django 5.1.1 on 2026-07-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0008_sellergoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do vendedor (para folha/contabilidade). Formato: 000.000.000-00', max_length=14, null=True),
        ),
    ]
