# Generated by Django 5.1.1 on 2026-07-04 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_accountant_fields'),
        ('sellers', '0011_normalize_cpf_digits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seller',
            constraint=models.UniqueConstraint(
                condition=models.Q(('cpf__isnull', False)),
                fields=('tenant', 'cpf'),
                name='unique_cpf_per_tenant',
            ),
        ),
    ]
