# Generated by Django 5.1.15 on 2026-07-12 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_tenant_period_start_day'),
        ('sellers', '0010_add_unique_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDayJustification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(choices=[('ATESTADO', 'Atestado'), ('FALTA', 'Falta'), ('FERIAS', 'Férias'), ('FOLGA', 'Folga'), ('AFASTAMENTO', 'Afastamento'), ('FERIADO', 'Feriado'), ('SEM_EXPEDIENTE', 'Sem expediente'), ('OUTRO', 'Outro')], max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_justifications_created', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_justifications', to='sellers.seller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_justifications', to='accounts.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_justifications_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'seller', 'date'], name='sellers_sel_tenant__d868d3_idx'), models.Index(fields=['tenant', 'date'], name='sellers_sel_tenant__151717_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'seller', 'date'), name='unique_day_justification_per_seller_date')],
            },
        ),
    ]
