# Generated by Django 5.1.1 on 2026-07-17 11:57

import app.apps.accounts.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0024_tenant_receivables_enabled'),
        ('sellers', '0013_sellerdayjustification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_name', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_document', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('payer_email', app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600)),
                ('payer_phone', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_zip_code', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_street', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_number', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_complement', app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600)),
                ('payer_neighborhood', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_city', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_state', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('amount_cents', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('instructions', models.CharField(blank=True, max_length=256)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(default='PAGARME', max_length=20)),
                ('provider_order_id', models.CharField(blank=True, max_length=100)),
                ('provider_charge_id', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('CRIANDO', 'Criando'), ('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCEL_PEND', 'Cancelamento pendente'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado'), ('FALHOU', 'Falhou')], default='CRIANDO', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('last_provider_status', models.CharField(blank=True, max_length=50)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('operation_error_code', models.CharField(blank=True, max_length=50)),
                ('operation_error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_created', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='sellers.seller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='receivables_tenant__f85fb6_idx'), models.Index(fields=['tenant', 'provider', 'provider_order_id'], name='receivables_tenant__344a45_idx'), models.Index(fields=['tenant', 'provider', 'provider_charge_id'], name='receivables_tenant__f0e52e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_boleto_tenant_idem')],
            },
        ),
    ]
