# Generated by Django 5.1.1 on 2026-07-20 12:33

import app.apps.accounts.fields
import app.apps.receivables.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0024_tenant_receivables_enabled'),
        ('commissions', '0007_remove_period_month_year_uniqueness'),
        ('sales', '0007_alter_sale_origin_saleimportbatch'),
        ('sellers', '0013_sellerdayjustification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_name', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_document', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('payer_email', app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600)),
                ('payer_phone', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_zip_code', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_street', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_number', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_complement', app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600)),
                ('payer_neighborhood', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_city', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('payer_state', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('amount_cents', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('instructions', models.CharField(blank=True, max_length=256)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(default='PAGARME', max_length=20)),
                ('provider_order_id', models.CharField(blank=True, max_length=100)),
                ('provider_charge_id', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('CRIANDO', 'Criando'), ('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCEL_PEND', 'Cancelamento pendente'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado'), ('FALHOU', 'Falhou')], default='CRIANDO', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('refund_reason', models.CharField(blank=True, max_length=255)),
                ('last_provider_status', models.CharField(blank=True, max_length=50)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('operation_error_code', models.CharField(blank=True, max_length=50)),
                ('operation_error_message', models.CharField(blank=True, max_length=255)),
                ('provider_barcode', models.CharField(blank=True, max_length=255)),
                ('provider_url', models.URLField(blank=True, max_length=500)),
                ('invoice_pdf', models.FileField(blank=True, max_length=255, upload_to=app.apps.receivables.models.invoice_pdf_upload_to)),
                ('invoice_pdf_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_xml', models.FileField(blank=True, max_length=255, upload_to=app.apps.receivables.models.invoice_xml_upload_to)),
                ('invoice_xml_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_created', to=settings.AUTH_USER_MODEL)),
                ('invoice_pdf_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_pdfs_uploaded', to=settings.AUTH_USER_MODEL)),
                ('invoice_xml_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_xmls_uploaded', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='sellers.seller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationOutbox',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_uuid', models.UUIDField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_key', models.CharField(max_length=150)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables_outbox_events', to='accounts.tenant')),
            ],
            options={
                'ordering': ['available_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableAllocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.PositiveIntegerField()),
                ('sale_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVERSED', 'Reversed')], default='ACTIVE', max_length=10)),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='receivables.boleto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_allocations', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_allocations', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionImpactReview',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_type', models.CharField(choices=[('ALLOCATION', 'Allocation'), ('REFUND', 'Refund'), ('CHARGEBACK', 'Chargeback')], max_length=12)),
                ('delta_sale_cents', models.IntegerField()),
                ('estimated_commission_delta_cents', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_impact_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_impact_reviews', to='sellers.seller')),
                ('seller_commission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_impact_reviews', to='commissions.sellercommission')),
                ('source_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_impact_reviews', to='commissions.commissionperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_impact_reviews', to='accounts.tenant')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_impact_reviews', to='receivables.receivableallocation')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivableNotificationDelivery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('recipient_hash', models.CharField(max_length=64)),
                ('delivery_key', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DEAD', 'Dead'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('skip_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outbox_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='receivables.integrationoutbox')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['tenant', 'status'], name='receivables_tenant__f85fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['tenant', 'provider', 'provider_order_id'], name='receivables_tenant__344a45_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['tenant', 'provider', 'provider_charge_id'], name='receivables_tenant__f0e52e_idx'),
        ),
        migrations.AddConstraint(
            model_name='boleto',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_boleto_tenant_idem'),
        ),
        migrations.AddIndex(
            model_name='integrationoutbox',
            index=models.Index(fields=['status', 'available_at'], name='receivables_status_9f694c_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationoutbox',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_key'), name='uniq_outbox_tenant_event_key'),
        ),
        migrations.AddIndex(
            model_name='receivableallocation',
            index=models.Index(fields=['tenant', 'status'], name='receivables_tenant__0150ad_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableallocation',
            index=models.Index(fields=['tenant', 'sale'], name='receivables_tenant__74f319_idx'),
        ),
        migrations.AddConstraint(
            model_name='receivableallocation',
            constraint=models.UniqueConstraint(fields=('tenant', 'boleto'), name='uniq_receivable_allocation_boleto'),
        ),
        migrations.AddConstraint(
            model_name='commissionimpactreview',
            constraint=models.UniqueConstraint(fields=('tenant', 'allocation', 'impact_type'), name='uniq_commission_impact_review'),
        ),
        migrations.AddConstraint(
            model_name='receivablenotificationdelivery',
            constraint=models.UniqueConstraint(fields=('tenant', 'delivery_key'), name='uniq_delivery_tenant_key'),
        ),
    ]
