# Generated by Django 5.1.1 on 2026-07-16 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0023_tenant_period_start_day'),
        ('sales', '0007_alter_sale_origin_saleimportbatch'),
        ('sellers', '0013_sellerdayjustification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_name', models.CharField(max_length=150)),
                ('payer_document', models.CharField(max_length=18)),
                ('payer_document_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('payer_phone', models.CharField(max_length=20)),
                ('payer_zip_code', models.CharField(max_length=9)),
                ('payer_street', models.CharField(max_length=150)),
                ('payer_number', models.CharField(max_length=20)),
                ('payer_complement', models.CharField(blank=True, max_length=100)),
                ('payer_neighborhood', models.CharField(max_length=100)),
                ('payer_city', models.CharField(max_length=100)),
                ('payer_state', models.CharField(max_length=2)),
                ('amount_cents', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('instructions', models.CharField(default='Apos o vencimento: multa de 2% e juros de 1% ao mes.', max_length=256)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('gateway', models.CharField(default='PAGARME', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=64)),
                ('gateway_charge_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('barcode', models.CharField(blank=True, max_length=160)),
                ('boleto_url', models.URLField(blank=True, max_length=500)),
                ('boleto_pdf_password', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos_created', to=settings.AUTH_USER_MODEL)),
                ('launched_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boleto', to='sales.sale')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='sellers.seller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
