# Generated by Django 5.1.1 on 2026-07-16 14:58

import app.apps.receivables.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='invoice_pdf',
            field=models.FileField(blank=True, max_length=500, upload_to=app.apps.receivables.models.invoice_upload_to),
        ),
        migrations.AddField(
            model_name='boleto',
            name='invoice_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boleto',
            name='invoice_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boleto_invoices_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boleto',
            name='invoice_xml',
            field=models.FileField(blank=True, max_length=500, upload_to=app.apps.receivables.models.invoice_upload_to),
        ),
    ]
