# Generated by Django 5.1.1 on 2026-07-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0002_boleto_invoice_pdf_boleto_invoice_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='customer_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
