# Generated by Django 5.1.1 on 2026-07-17 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_tenant_receivables_enabled'),
        ('commissions', '0007_remove_period_month_year_uniqueness'),
        ('receivables', '0003_receivable_allocation'),
        ('sellers', '0013_sellerdayjustification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionImpactReview',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impact_type', models.CharField(choices=[('ALLOCATION', 'Allocation'), ('REFUND', 'Refund'), ('CHARGEBACK', 'Chargeback')], max_length=12)),
                ('delta_sale_cents', models.IntegerField()),
                ('estimated_commission_delta_cents', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_impact_reviews', to='receivables.receivableallocation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_impact_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_impact_reviews', to='sellers.seller')),
                ('seller_commission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_impact_reviews', to='commissions.sellercommission')),
                ('source_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_impact_reviews', to='commissions.commissionperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_impact_reviews', to='accounts.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'allocation', 'impact_type'), name='uniq_commission_impact_review')],
            },
        ),
    ]
