# Generated by Django 5.1.1 on 2026-07-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0005_boleto_invoice_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='provider_barcode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='boleto',
            name='provider_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
