# Generated by Django 5.1.1 on 2026-07-17 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_tenant_receivables_enabled'),
        ('receivables', '0006_boleto_delivery_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivableNotificationDelivery',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('recipient_hash', models.CharField(max_length=64)),
                ('delivery_key', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DEAD', 'Dead'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('skip_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outbox_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='receivables.integrationoutbox')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'delivery_key'), name='uniq_delivery_tenant_key')],
            },
        ),
    ]
