# Generated by Django 5.1.1 on 2026-06-20 02:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('LINK', 'Venda via Link de Pagamento'), ('MANUAL', 'Lançamento Manual')], max_length=10)),
                ('amount', models.PositiveIntegerField(help_text='Valor em centavos')),
                ('sale_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lancadas', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='sellers.seller')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'seller', 'sale_date'], name='sales_sale_tenant__05e004_idx'), models.Index(fields=['tenant', 'origin'], name='sales_sale_tenant__576262_idx')],
            },
        ),
    ]
