# Generated by Django 5.1.1 on 2026-06-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_business_rules_revision'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_sale_seller__27b7f0_idx',
            old_name='sales_sale_selle_3c02cb_idx',
        ),
    ]
