# Generated by Django 5.1.1 on 2026-07-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_sales_sale_selle_3c02cb_idx_sales_sale_seller__27b7f0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('ESTORNADA', 'Estornada')], default='ATIVA', max_length=10),
        ),
    ]
