# Generated by Django 5.1.15 on 2026-07-10 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_tenant_skip_national_holidays_and_more'),
        ('sales', '0005_alter_sale_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleChangeLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('UPDATE', 'Atualização'), ('CREATE_IMPORT', 'Criação por Importação'), ('VOID', 'Estorno')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_changes', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_change_logs', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'sale'], name='sales_salec_tenant__95317f_idx'), models.Index(fields=['changed_at'], name='sales_salec_changed_3e18ef_idx')],
            },
        ),
    ]
