# Generated by Django 5.1.15 on 2026-07-10 02:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_tenant_skip_national_holidays_and_more'),
        ('sales', '0006_salechangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='origin',
            field=models.CharField(choices=[('LINK', 'Venda via Link de Pagamento'), ('MANUAL', 'Lançamento Manual'), ('IMPORTADA', 'Importada')], max_length=10),
        ),
        migrations.CreateModel(
            name='SaleImportBatch',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IMPORTED', 'Importado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_import_batches', to='accounts.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'file_hash'], name='sales_salei_tenant__3ce81d_idx'), models.Index(fields=['uploaded_at'], name='sales_salei_uploade_e94293_idx')],
            },
        ),
    ]
