# Generated by Django 5.1.1 on 2026-06-23 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_tenant_slug'),
        ('sellers', '0004_make_user_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPeriod',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PARCIALMENTE_FECHADA', 'Parcialmente Fechada'), ('FECHADA', 'Fechada'), ('PARCIALMENTE_PAGA', 'Parcialmente Paga'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=25)),
                ('expected_working_days', models.PositiveSmallIntegerField(default=22, help_text='Dias trabalhados esperados no mes')),
                ('notes', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_adjusted', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_cancelled', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_closed', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_paid', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_periods', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga'), ('AJUSTADA', 'Ajustada'), ('REABERTA', 'Reaberta'), ('CANCELADA', 'Cancelada')], default='ABERTA', help_text='Status financeiro individual do vendedor', max_length=20)),
                ('operational_status', models.CharField(choices=[('PRONTO', 'Pronto'), ('PENDENTE', 'Pendente'), ('SEM_LANCAMENTO', 'Sem Lancamento')], default='SEM_LANCAMENTO', help_text='Status operacional (dias lancados vs esperados)', max_length=20)),
                ('total_sold_amount', models.PositiveIntegerField(default=0, help_text='Total vendido em centavos (ao vivo se ABERTA)')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.01, max_digits=5)),
                ('commission_amount', models.PositiveIntegerField(default=0, help_text='Comissao devida em centavos')),
                ('expected_working_days', models.PositiveSmallIntegerField(default=22, help_text='Dias esperados (congelado no fechamento)')),
                ('submitted_days_count', models.PositiveSmallIntegerField(default=0, help_text='Dias com lancamento manual')),
                ('missing_days_count', models.PositiveSmallIntegerField(default=0, help_text='Dias faltantes')),
                ('frozen_total_sold_amount', models.PositiveIntegerField(blank=True, help_text='Total congelado no fechamento', null=True)),
                ('frozen_commission_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('frozen_commission_amount', models.PositiveIntegerField(blank=True, help_text='Comissao congelada no fechamento', null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.PositiveIntegerField(blank=True, help_text='Valor efetivamente pago em centavos', null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_closed', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_paid', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_commissions', to='commissions.commissionperiod')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_reopened', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_amount', models.PositiveIntegerField(help_text='Valor da comissao antes do ajuste em centavos')),
                ('new_amount', models.PositiveIntegerField(help_text='Valor da comissao depois do ajuste em centavos')),
                ('difference', models.IntegerField(help_text='Diferenca (positivo = aumento, negativo = reducao) em centavos')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('seller_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='commissions.sellercommission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commissionperiod',
            index=models.Index(fields=['tenant', 'status'], name='commissions_tenant__bc6d1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commissionperiod',
            unique_together={('tenant', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='sellercommission',
            unique_together={('period', 'seller')},
        ),
    ]
