# Generated by Django 5.1.1 on 2026-06-20 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPeriod',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_CONFERENCIA', 'Em Conferência'), ('ENVIADA_FINANCEIRO', 'Enviada ao Financeiro'), ('APROVADA', 'Aprovada para Pagamento'), ('PAGA', 'Paga')], default='ABERTA', max_length=20)),
                ('sent_to_financial_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_periods', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SellerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sold_amount', models.PositiveIntegerField(default=0, help_text='Total vendido em centavos')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=0.01, max_digits=5)),
                ('commission_amount', models.PositiveIntegerField(default=0, help_text='Comissão devida em centavos')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_commissions', to='commissions.commissionperiod')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='sellers.seller')),
            ],
        ),
        migrations.AddIndex(
            model_name='commissionperiod',
            index=models.Index(fields=['tenant', 'status'], name='commissions_tenant__bc6d1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commissionperiod',
            unique_together={('tenant', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='sellercommission',
            unique_together={('period', 'seller')},
        ),
    ]
