# Generated by Django 5.1.1 on 2026-06-25 02:20

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_options_user_user_tenant_role_idx_and_more'),
        ('commissions', '0001_initial'),
        ('sellers', '0006_unique_tenant_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commissionperiod',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sellercommission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='commissionperiod',
            name='month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='sellercommission',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga'), ('AJUSTADA', 'Ajustada'), ('REABERTA', 'Reaberta'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', help_text='Status financeiro individual do vendedor', max_length=20),
        ),
        migrations.AddIndex(
            model_name='commissionperiod',
            index=models.Index(fields=['month', 'year'], name='commissions_month_431056_idx'),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['period', 'status'], name='commissions_period__cedbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='sellercommission',
            index=models.Index(fields=['seller', 'status'], name='commissions_seller__28f4ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'month', 'year'), name='unique_period_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sellercommission',
            constraint=models.UniqueConstraint(fields=('period', 'seller'), name='unique_commission_per_seller'),
        ),
    ]
