# Generated by Django 5.1.1 on 2026-07-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_add_accounting_tracking'),
        ('sellers', '0010_add_unique_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellercommission',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='sellers.seller'),
        ),
    ]
