# Generated by Django 5.1.1 on 2026-06-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_business_rules_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionperiod',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='commissionperiod',
            name='sent_to_financial_at',
        ),
        migrations.AlterField(
            model_name='sellercommission',
            name='commission_amount',
            field=models.PositiveIntegerField(default=0, help_text='Comissao devida em centavos'),
        ),
    ]
