# Generated by Django 5.1.1 on 2026-07-10 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_tenant_skip_national_holidays_and_more'),
        ('commissions', '0005_period_date_ranges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commissionperiod',
            name='unique_period_per_tenant',
        ),
        migrations.AddConstraint(
            model_name='commissionperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELADA'), _negated=True), fields=('tenant', 'month', 'year'), name='unique_period_per_tenant'),
        ),
    ]
