# Generated by Django 5.1.1 on 2026-07-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_remove_commissionperiod_unique_period_per_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commissionperiod',
            name='unique_period_per_tenant',
        ),
    ]
