# Generated by Django 5.1.1 on 2026-07-03 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_tenant_ranking_visible_to_sellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('ESSENCIAL', 'Essencial (ate 5 vendedores)'), ('PROFISSIONAL', 'Profissional (ate 15 vendedores)'), ('PLUS', 'Plus (ate 30 vendedores)'), ('ENTERPRISE', 'Enterprise (ilimitado)')], max_length=20)),
                ('status', models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled')], default='TRIALING', max_length=10)),
                ('gateway_subscription_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(default=0, help_text='Valor em centavos')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='billing_sub_status_948046_idx'), models.Index(fields=['gateway_subscription_id'], name='billing_sub_gateway_6d0a64_idx')],
            },
        ),
    ]
