# Generated by Django 5.1.1 on 2026-07-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('TRIALING', 'Periodo de teste'), ('ACTIVE', 'Ativa'), ('PAST_DUE', 'Pagamento pendente'), ('CANCELED', 'Cancelada')], default='TRIALING', max_length=10),
        ),
    ]
