# Generated by Django 5.1.1 on 2026-06-20 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='orders.paymentlink')),
            ],
            options={
                'indexes': [models.Index(fields=['payment_link', 'clicked_at'], name='analytics_l_payment_a8e8ef_idx')],
            },
        ),
    ]
