# Generated by Django 5.1.1 on 2026-06-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkclick',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='linkclick',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
