# Generated by Django 5.1.1 on 2026-07-16 15:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.apps.accounts.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0023_tenant_period_start_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                (
                    "email",
                    app.apps.accounts.fields.EncryptedCharField(
                        blank=True, max_length=600
                    ),
                ),
                (
                    "phone",
                    app.apps.accounts.fields.EncryptedCharField(
                        blank=True, max_length=600
                    ),
                ),
                (
                    "document",
                    app.apps.accounts.fields.EncryptedCharField(
                        blank=True, max_length=600
                    ),
                ),
                ("document_type", models.CharField(blank=True, max_length=4)),
                ("email_hash", models.CharField(blank=True, max_length=64)),
                ("phone_hash", models.CharField(blank=True, max_length=64)),
                ("document_hash", models.CharField(blank=True, max_length=64)),
                (
                    "zip_code",
                    app.apps.accounts.fields.EncryptedCharField(
                        blank=True, max_length=600
                    ),
                ),
                (
                    "street",
                    app.apps.accounts.fields.EncryptedCharField(
                        blank=True, max_length=600
                    ),
                ),
                (
                    "number",
                    app.apps.accounts.fields.EncryptedCharField(
                        blank=True, max_length=600
                    ),
                ),
                (
                    "complement",
                    app.apps.accounts.fields.EncryptedCharField(
                        blank=True, max_length=600
                    ),
                ),
                (
                    "neighborhood",
                    app.apps.accounts.fields.EncryptedCharField(
                        blank=True, max_length=600
                    ),
                ),
                (
                    "city",
                    app.apps.accounts.fields.EncryptedCharField(
                        blank=True, max_length=600
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=2)),
                ("notes", app.apps.accounts.fields.EncryptedTextField(blank=True)),
                (
                    "marketing_consent",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Nao informado"),
                            ("GRANTED", "Autorizado"),
                            ("REVOKED", "Revogado"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("marketing_consent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "marketing_consent_source",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marketing_consent_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_consents_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("BOLETO", "Boleto"),
                            ("PAYMENT_LINK", "Link de pagamento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_uuid", models.UUIDField()),
                ("seller_name", models.CharField(blank=True, max_length=150)),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
    ]
