# Generated by Django 5.1.1 on 2026-07-20 12:33

import app.apps.accounts.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0024_tenant_receivables_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', app.apps.accounts.fields.EncryptedCharField(max_length=600)),
                ('email', app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600)),
                ('phone', app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600)),
                ('document', app.apps.accounts.fields.EncryptedCharField(blank=True, max_length=600)),
                ('document_type', models.CharField(blank=True, max_length=4)),
                ('name_hash', models.CharField(blank=True, max_length=64)),
                ('document_hash', models.CharField(blank=True, max_length=64)),
                ('email_hash', models.CharField(blank=True, max_length=64)),
                ('phone_hash', models.CharField(blank=True, max_length=64)),
                ('operational_consent', models.CharField(choices=[('UNKNOWN', 'Nao informado'), ('GRANTED', 'Autorizado'), ('REVOKED', 'Revogado')], default='UNKNOWN', max_length=10)),
                ('marketing_consent', models.CharField(choices=[('UNKNOWN', 'Nao informado'), ('GRANTED', 'Autorizado'), ('REVOKED', 'Revogado')], default='UNKNOWN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('BOLETO', 'Boleto'), ('PAYMENT_LINK', 'Payment Link')], max_length=20)),
                ('source_uuid', models.UUIDField()),
                ('seller_name', models.CharField(blank=True, max_length=150)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_activities', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerIdentityConflict',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier_type', models.CharField(choices=[('DOCUMENT', 'Documento'), ('EMAIL', 'E-mail'), ('PHONE', 'Telefone')], max_length=10)),
                ('identifier_hash', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=20)),
                ('source_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflicting_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_conflicts_conflicting', to='customers.customer')),
                ('selected_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_conflicts_selected', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_identity_conflicts', to='accounts.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('document_hash', ''), _negated=True), fields=('tenant', 'document_hash'), name='uniq_customer_tenant_document'),
        ),
        migrations.AddConstraint(
            model_name='customeractivity',
            constraint=models.UniqueConstraint(fields=('tenant', 'source', 'source_uuid'), name='uniq_customer_activity_source'),
        ),
        migrations.AddConstraint(
            model_name='customeridentityconflict',
            constraint=models.UniqueConstraint(fields=('tenant', 'identifier_type', 'identifier_hash', 'selected_customer', 'conflicting_customer'), name='uniq_customer_identity_conflict'),
        ),
    ]
