# Generated by Django 5.1.1 on 2026-07-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_tenant_receivables_enabled'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeractivity',
            name='source',
            field=models.CharField(choices=[('BOLETO', 'Boleto'), ('PAYMENT_LINK', 'Payment Link')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='customeridentityconflict',
            constraint=models.UniqueConstraint(fields=('tenant', 'identifier_type', 'identifier_hash', 'selected_customer', 'conflicting_customer'), name='uniq_customer_identity_conflict'),
        ),
    ]
