# Generated by Django 5.1.1 on 2026-07-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="name_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
