# Generated by Django 5.1.1 on 2026-07-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_webhook_credentials'),
        ('webhooks', '0002_add_tenant_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='gateway_event_id',
            field=models.CharField(blank=True, help_text='ID unico do evento no gateway (ex: evt_xxx no Pagar.me)', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['gateway_event_id'], name='webhooks_we_gateway_09402f_idx'),
        ),
    ]
