# Generated by Django 5.1.1 on 2026-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_add_gateway_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='skip_reason',
            field=models.TextField(blank=True, help_text='Motivo do skip (evento estrangeiro)', null=True),
        ),
    ]
