# Generated by Codex on 2026-07-07

from django.db import migrations, models
from django.db.models import Count, Q


def assert_no_duplicate_gateway_event_ids(apps, schema_editor):
    WebhookEvent = apps.get_model('webhooks', 'WebhookEvent')
    duplicates = list(
        WebhookEvent.objects.exclude(gateway_event_id__isnull=True)
        .values('gateway', 'gateway_event_id')
        .annotate(count=Count('id'))
        .filter(count__gt=1)[:10]
    )
    if duplicates:
        details = ', '.join(
            f"{item['gateway']}:{item['gateway_event_id']} ({item['count']})"
            for item in duplicates
        )
        raise RuntimeError(
            'Duplicate WebhookEvent gateway_event_id per gateway found: '
            f'{details}'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_webhookevent_skip_reason'),
    ]

    operations = [
        migrations.RunPython(
            assert_no_duplicate_gateway_event_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='gateway_event_id',
            field=models.CharField(
                blank=True,
                help_text='ID unico do evento no gateway (ex: evt_xxx no Pagar.me)',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(
                condition=Q(gateway_event_id__isnull=False),
                fields=('gateway', 'gateway_event_id'),
                name='webhook_event_gateway_event_id_uniq',
            ),
        ),
    ]
