# Generated by Django 5.1.1 on 2026-07-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_webhookevent_gateway_scoped_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='RECEIVED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['gateway', 'status'], name='webhooks_we_gateway_b33b12_idx'),
        ),
    ]
