# Generated by Django 5.1.1 on 2026-07-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_tenant_receivables_enabled'),
        ('webhooks', '0006_webhookevent_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='correlation_id',
            field=models.CharField(blank=True, help_text='ID de correlacao para tracing end-to-end', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='effect_reference',
            field=models.CharField(blank=True, help_text='Referencia do efeito financeiro (ex: pagarme:{tenant}:{charge}:paid)', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processor_version',
            field=models.CharField(blank=True, default='v1', help_text='Versao do processador que tratou o evento', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='receipt_id',
            field=models.CharField(blank=True, help_text='ID de recibo gerado pelo Merito ao aceitar o webhook', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('IGNORED', 'Ignored')], default='RECEIVED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'processing_started_at'], name='webhooks_we_status_e3eb55_idx'),
        ),
    ]
