# Generated by Django 5.1.1 on 2024-09-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_pagarmetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagarmetransaction',
            name='link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
