# Generated by Django 5.1.1 on 2024-11-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_pagarmetransaction_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagarMePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('total_amount', models.IntegerField()),
                ('max_installments', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=20)),
                ('link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagarmetransaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='PagarMeOrder',
        ),
        migrations.DeleteModel(
            name='PagarMeTransaction',
        ),
    ]
