"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# APIs e Integrações
WHATSAPP_API_KEY = config('WHATSAPP_API_KEY', default=config('API_KEY_INSTANCIA', default=''))
WHATSAPP_INSTANCE = config('WHATSAPP_INSTANCE', default=config('INSTANCE', default=''))
WHATSAPP_API_BASE_URL = config('WHATSAPP_API_BASE_URL', default='')
WHATSAPP_ALLOW_SHARED_INSTANCE = config('WHATSAPP_ALLOW_SHARED_INSTANCE', default=False, cast=bool)
SERVICE_FQDN_WEB = config('SERVICE_FQDN_WEB', default='localhost')
FERNET_KEY = config('FERNET_KEY', default='')

VAPID_PUBLIC_KEY = config('VAPID_PUBLIC_KEY', default='')
VAPID_PRIVATE_KEY = config('VAPID_PRIVATE_KEY', default='')
VAPID_CONTACT_EMAIL = config('VAPID_CONTACT_EMAIL', default='contato@vidalys.com.br')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app.apps.accounts",
    "app.apps.sellers",
    "app.apps.orders",
    "app.apps.payments",
    "app.apps.sales",
    "app.apps.commissions",
    "app.apps.webhooks",
    "app.apps.notifications",
    "app.apps.audit",
    "app.apps.dashboard",
    "app.apps.api",
    "app.apps.analytics",
    "app.apps.billing",
    "app.apps.freight",
    "app.apps.receivables",

    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "app.apps.accounts.middleware.TrialEnforcementMiddleware",
]

ROOT_URLCONF = "app.config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "app.apps.accounts.context_processors.trial_status",
                "app.apps.accounts.context_processors.global_context",
            ],
        },
    },
]

WSGI_APPLICATION = "app.config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",  # Para produção, prefira um banco como PostgreSQL ou MySQL
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]  # Onde o Django vai procurar os arquivos estáticos
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # Para onde os arquivos serão coletados ao rodar collectstatic
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")  # Diretório de arquivos de mídia

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"  # Usando Whitenoise para produção

# Configurações para Whitenoise (servidor de arquivos estáticos em produção)
# Já incluído no MIDDLEWARE, não há mais ajustes necessários aqui

# E-mail (console no dev, SMTP em producao)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@querolink.com.br')
SERVER_EMAIL = config('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'accounts.User'

# Sessões e Login
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

LOGIN_URL = 'dashboard:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'dashboard:login'

# CSRF
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)
CORS_ALLOW_CREDENTIALS = True

# Security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/hour',
        'anon': '100/hour',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Mérito API',
    'DESCRIPTION': 'API de gestao de comissoes multi-tenant',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

from datetime import timedelta

WEBHOOK_AUTH_REQUIRED = config('WEBHOOK_AUTH_REQUIRED', default=True, cast=bool)

PAGARME_BOLETO_FINE_ENABLED = config(
    'PAGARME_BOLETO_FINE_ENABLED', default=False, cast=bool,
)
PAGARME_BOLETO_INTEREST_ENABLED = config(
    'PAGARME_BOLETO_INTEREST_ENABLED', default=False, cast=bool,
)

PLAN_PRICES = {
    'STARTER': config('PLAN_PRICE_STARTER', default=14700, cast=int),
    'PRO': config('PLAN_PRICE_PRO', default=29700, cast=int),
    'BUSINESS': config('PLAN_PRICE_BUSINESS', default=49700, cast=int),
}
PLAN_SELLER_LIMITS = {
    'STARTER': 5,
    'PRO': 15,
    'BUSINESS': 50,
}
PLAN_FEATURES = {
    'STARTER': {
        'links_pagamento': True,
        'whatsapp_lembretes': True,
        'web_push': False,
        'relatorio_pdf': False,
        'export_contabil': False,
        'importacao_csv': False,
        'previa_fechamento': False,
        'boletos': False,
    },
    'PRO': {
        'links_pagamento': True,
        'whatsapp_lembretes': True,
        'web_push': True,
        'relatorio_pdf': True,
        'export_contabil': True,
        'importacao_csv': True,
        'previa_fechamento': True,
        'boletos': True,
    },
    'BUSINESS': {
        'links_pagamento': True,
        'whatsapp_lembretes': True,
        'web_push': True,
        'relatorio_pdf': True,
        'export_contabil': True,
        'importacao_csv': True,
        'previa_fechamento': True,
        'boletos': True,
    },
}

MP_ACCESS_TOKEN = config('MP_ACCESS_TOKEN', default='')
MP_PUBLIC_KEY = config('MP_PUBLIC_KEY', default='')
MP_WEBHOOK_SECRET = config('MP_WEBHOOK_SECRET', default='')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', default=30, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_LIFETIME_DAYS', default=7, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('JWT_SIGNING_KEY', default=None) or SECRET_KEY,
}
