# Generated by Django 5.1.1 on 2026-06-20 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(default='pagarme', max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('pix', 'Pix'), ('boleto', 'Boleto'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('installments', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CHARGEBACK', 'Chargeback')], default='PENDING', max_length=20)),
                ('raw_callback_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'), models.Index(fields=['gateway_transaction_id'], name='payments_pa_gateway_2a3159_idx')],
            },
        ),
    ]
